### ISSUE TITLE
Have to wait a lot of time to several consequence STOR commands to be executed

### ISSUE THREAD

**Issue by MikhailKlemin** [dutchcoders/goftp#23]
Hi
I followed example and it works fine. 
However after each STOR command I have to wait ~ 3 minutes... 
When in debug mode the server says :- `220 You will be disconnected after 3 minutes of inactivity.`  and looks like it is when next STOR command is executed. 

```
if err := ftp.Stor("/myfile.txt", mydata); err != nil {
	log.Fatal(err)
}
// Then it takes 3 minute to get here
if err := ftp.Stor("/myfile2.txt", mydata2); err != nil {
	log.Fatal(err)
}

```

**Comment by ozanh** [comment]
Hi,
I have created #21 pull request, probably addressing this, but it's not merged by authors yet. Can you please try my repo and check everything is OK?

**Comment by MikhailKlemin** [comment]
Hi Ozanh!
Works fine, thanks a lot!
What was wrong?

**Comment by MikhailKlemin** [comment]
I think I keep it open until

**Comment by nl5887** [comment]
PR #21  has been merged, closing now. Thx.
