### ISSUE TITLE
Example Not Functional

### ISSUE THREAD

**Issue by pnovotnak** [dutchcoders/goftp#5]
Example is not functional :-1:

**Comment by nl5887** [comment]
Thanks for your constructive feedback :+1:

**Comment by pnovotnak** [comment]
![screen shot 2015-07-15 at 4 30 19 pm](https://cloud.githubusercontent.com/assets/5713245/8712257/eed4c812-2b0e-11e5-9841-741071298963.png)

**Comment by javierbq** [comment]
Sarcasm doesn't fix broken documentation.

**Comment by nl5887** [comment]
Nope, pull requests will. Will look into this issue and fix it.
